In [ ]:
import pandas as pd

data = {'Name': [ 'Alice', 'Bob', 'Charlie'],
       'Age': [25, 30, 35],
       'City': ['New York', 'Paris', 'London']}

df = pd.DataFrame(data)

print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London

In [ ]:
import numpy as np

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/data science/people_data.csv')
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [ ]:
df.head(10)

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/data science/titanic.csv')
df

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df.head(10)

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
5,6,"Moran, Mr. James",3,male,NaN,0,0,330877,8.4583,NaN,Q,0
6,7,"McCarthy, Mr. Timothy J",1,male,54.0,0,0,17463,51.8625,E46,S,0
7,8,"Palsson, Master. Gosta Leonard",3,male,2.0,3,1,349909,21.0750,NaN,S,0
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",3,female,27.0,0,2,347742,11.1333,NaN,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",2,female,14.0,1,0,237736,30.0708,NaN,C,1

In [ ]:
  df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [ ]:
shape=df.shape
print(shape)

(891, 12)

In [ ]:
   df.isnull().values.any()

np.True_

In [ ]:
data = {'Name': [ 'Alice', 'Bob', 'Charlie'],
       'Age': [25, 30, 35],
       'City': ['New York', 'Paris', 'London'],
        'Country':['USA','USA','USA']}

In [ ]:
df = pd.DataFrame(data)

print(df)

      Name  Age      City Country
0    Alice   25  New York     USA
1      Bob   30     Paris     USA
2  Charlie   35    London     USA

In [ ]:
df=df.drop('City', axis=1) # Specify axis=1 to drop a column
df

      Name  Age Country
0    Alice   25     USA
1      Bob   30     USA
2  Charlie   35     USA

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/data science/titanic.csv')
df. rename(columns={ 'Age': 'Years'}, inplace=True)
df

,PassengerId,Name,Pclass,Sex,Years,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df.to_csv('output.csv', index=False)
df

,PassengerId,Name,Pclass,Sex,Years,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df[df['Years'] > 30]

,PassengerId,Name,Pclass,Sex,Years,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
6,7,"McCarthy, Mr. Timothy J",1,male,54.0,0,0,17463,51.8625,E46,S,0
11,12,"Bonnell, Miss. Elizabeth",1,female,58.0,0,0,113783,26.5500,C103,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,"Vander Cruyssen, Mr. Victor",3,male,47.0,0,0,345765,9.0000,NaN,S,0
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,female,56.0,0,1,11767,83.1583,C50,C,1
881,882,"Markun, Mr. Johann",3,male,33.0,0,0,349257,7.8958,NaN,S,0
885,886,"Rice, Mrs. William (Margaret Norton)",3,female,39.0,0,5,382652,29.1250,NaN,Q,0
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df['Age_Group'] = np.where(df['Years'] < 30, 'Young', 'Old')
print(df)

     PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2              3                             Heikkinen, Miss. Laina       3
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4              5                           Allen, Mr. William Henry       3
..           ...                                                ...     ...
886          887                              Montvila, Rev. Juozas       2
887          888                       Graham, Miss. Margaret Edith       1
888          889           Johnston, Miss. Catherine Helen "Carrie"       3
889          890                              Behr, Mr. Karl Howell       1
890          891                                Dooley, Mr. Patrick       3

        Sex  Years  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male   22.0      1      0         A/5 21171   7.2500   NaN        S
1    female   38.0      1      0          PC 17599  71.2833   C85        C
2    female   26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3    female   35.0      1      0            113803  53.1000  C123        S
4      male   35.0      0      0            373450   8.0500   NaN        S
..      ...    ...    ...    ...               ...      ...   ...      ...
886    male   27.0      0      0            211536  13.0000   NaN        S
887  female   19.0      0      0            112053  30.0000   B42        S
888  female    NaN      1      2        W./C. 6607  23.4500   NaN        S
889    male   26.0      0      0            111369  30.0000  C148        C
890    male   32.0      0      0            370376   7.7500   NaN        Q

     Survived Age_Group
0           0     Young
1           1       Old
2           1     Young
3           1       Old
4           0       Old
..        ...       ...
886         0     Young
887         1     Young
888         0       Old
889         1     Young
890         0       Old

[891 rows x 13 columns]

In [ ]:
sorted_df = df.sort_values(by='Years', ascending=False)
sorted_df

,PassengerId,Name,Pclass,Sex,Years,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived,Age_Group
630,631,"Barkworth, Mr. Algernon Henry Wilson",1,male,80.0,0,0,27042,30.0000,A23,S,1,Old
851,852,"Svensson, Mr. Johan",3,male,74.0,0,0,347060,7.7750,NaN,S,0,Old
493,494,"Artagaveytia, Mr. Ramon",1,male,71.0,0,0,PC 17609,49.5042,NaN,C,0,Old
96,97,"Goldschmidt, Mr. George B",1,male,71.0,0,0,PC 17754,34.6542,A5,C,0,Old
116,117,"Connors, Mr. Patrick",3,male,70.5,0,0,370369,7.7500,NaN,Q,0,Old
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",3,male,NaN,0,0,2629,7.2292,NaN,C,0,Old
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",3,female,NaN,8,2,CA. 2343,69.5500,NaN,S,0,Old
868,869,"van Melkebeke, Mr. Philemon",3,male,NaN,0,0,345777,9.5000,NaN,S,0,Old
878,879,"Laleff, Mr. Kristo",3,male,NaN,0,0,349217,7.8958,NaN,S,0,Old
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,Old

In [ ]:
print(df['Years'].mean()) # Correct way to calculate the mean of the 'Years' column
df

29.69911764705882

,PassengerId,Name,Pclass,Sex,Years,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived,Age_Group
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,Young
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,Old
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,Young
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1,Old
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0,Old
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0,Young
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1,Young
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,Old
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1,Young
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0,Old

In [ ]:
print(df['Years'].std())

14.526497332334044

In [ ]:
print( df['Years'].median())

28.0

In [ ]:
data = {'Name': [ 'Alice', 'Bob', 'Charlie'],
       'Age': [25, 30, 35],
       'City': ['New York', 'Paris', 'London'],
        'Country':['USA','USA','USA']}


df = pd.DataFrame(data)
df

      Name  Age      City Country
0    Alice   25  New York     USA
1      Bob   30     Paris     USA
2  Charlie   35    London     USA

In [ ]:
unique_cities = df['City'].unique()
print(unique_cities)

['New York' 'Paris' 'London']

In [ ]:
n = len(pd.unique(df['City']))
print(n)

3

In [ ]:

df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
vertical_concat = pd.concat([df1, df2], axis=0)
print("Vertical:")
display(vertical_concat)

Vertical:

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [ ]:
df1 = pd.DataFrame({'ID': [1, 2, 3, 5, 7, 8],
                    'Name': ['Sam', 'John', 'Bridge',
                             'Edge', 'Joe', 'Hope']})

df2 = pd.DataFrame({'ID': [1, 2, 4, 5, 6, 8, 9],
                    'Marks': [67, 92, 75, 83, 69, 56, 81]})
df = pd.merge(df1, df2, on="ID")
print(df)

   ID  Name  Marks
0   1   Sam     67
1   2  John     92
2   5  Edge     83
3   8  Hope     56

In [ ]:
print("\nDrop rows where all values are NaN:\n", df.dropna(how='all'))

NameError: name 'cleaned_df' is not defined

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/data science/titanic.csv')

print("\nDrop rows where all values are NaN:\n", df.dropna(how='all'))

Drop rows where all values are NaN:
      PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2              3                             Heikkinen, Miss. Laina       3
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4              5                           Allen, Mr. William Henry       3
..           ...                                                ...     ...
886          887                              Montvila, Rev. Juozas       2
887          888                       Graham, Miss. Margaret Edith       1
888          889           Johnston, Miss. Catherine Helen "Carrie"       3
889          890                              Behr, Mr. Karl Howell       1
890          891                                Dooley, Mr. Patrick       3

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S
1    female  38.0      1      0          PC 17599  71.2833   C85        C
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3    female  35.0      1      0            113803  53.1000  C123        S
4      male  35.0      0      0            373450   8.0500   NaN        S
..      ...   ...    ...    ...               ...      ...   ...      ...
886    male  27.0      0      0            211536  13.0000   NaN        S
887  female  19.0      0      0            112053  30.0000   B42        S
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
889    male  26.0      0      0            111369  30.0000  C148        C
890    male  32.0      0      0            370376   7.7500   NaN        Q

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 12 columns]

In [ ]:
data = {'date': ['2023-01-01', '2023-02-15', '2023-03-20']}
df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date'])
print(df['date'])

0   2023-01-01
1   2023-02-15
2   2023-03-20
Name: date, dtype: datetime64[ns]

In [ ]:
df = pd.read_excel(r'/content/drive/MyDrive/data science/weather_data_excel (1) (2) (1).xlsx')
df

                    day     city  temperature  windspeed   event
0   2017-01-01 00:00:00  newyork           32          6    Rain
1   2017-04-01 00:00:00  newyork           36          7   Sunny
2   2017-05-01 00:00:00  newyork           28         12    Snow
3   2017-06-01 00:00:00  newyork           33          7   Sunny
4   2017-07-01 00:00:00   mumbai           90          5   Sunny
5   2017-08-01 00:00:00   mumbai           85         12     Fog
6   2017-09-01 00:00:00   mumbai           87         15     Fog
7   2017-10-01 00:00:00   mumbai           92          5    Rain
8   2017-11-01 00:00:00    paris           45         20   Sunny
9   2017-12-01 00:00:00    paris           50         13  Cloudy
10           01-13-2017    paris           54          8  Cloudy
11           01-14-2017    paris           42         10  Cloudy

In [ ]:
df['day'] = pd.to_datetime(df['day'])
print(df['day'])

0    2017-01-01
1    2017-04-01
2    2017-05-01
3    2017-06-01
4    2017-07-01
5    2017-08-01
6    2017-09-01
7    2017-10-01
8    2017-11-01
9    2017-12-01
10   2017-01-13
11   2017-01-14
Name: day, dtype: datetime64[ns]

In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
raw_data = {'name': ['Willard Morris', 'Al Jennings', 'Omar Mullins', 'Spencer McDaniel'],
'age': [20, 19, 22, 21],
'favorite_color': ['blue', 'red', 'yellow', "green"],
'grade': [88, 92, 95, 70],
'birth_date': ['01-02-1996', '08-05-1997', '04-28-1996', '12-16-1995']}
df = pd.DataFrame(raw_data, index = ['Willard Morris', 'Al Jennings', 'Omar Mullins', 'Spencer McDaniel'])
df

                              name  age favorite_color  grade  birth_date
Willard Morris      Willard Morris   20           blue     88  01-02-1996
Al Jennings            Al Jennings   19            red     92  08-05-1997
Omar Mullins          Omar Mullins   22         yellow     95  04-28-1996
Spencer McDaniel  Spencer McDaniel   21          green     70  12-16-1995

In [3]:
df['year'] = pd.DatetimeIndex(df['birth_date']).year
df.head()

,name,age,favorite_color,grade,birth_date,year
Willard Morris,Willard Morris,20,blue,88,01-02-1996,1996
Al Jennings,Al Jennings,19,red,92,08-05-1997,1997
Omar Mullins,Omar Mullins,22,yellow,95,04-28-1996,1996
Spencer McDaniel,Spencer McDaniel,21,green,70,12-16-1995,1995

In [4]:
df['month'] = pd.DatetimeIndex(df['birth_date']).month
df.head()

,name,age,favorite_color,grade,birth_date,year,month
Willard Morris,Willard Morris,20,blue,88,01-02-1996,1996,1
Al Jennings,Al Jennings,19,red,92,08-05-1997,1997,8
Omar Mullins,Omar Mullins,22,yellow,95,04-28-1996,1996,4
Spencer McDaniel,Spencer McDaniel,21,green,70,12-16-1995,1995,12